# Sudo-enabled Ubuntu Trusty VM
dist: trusty
sudo: required


# Build, test and deploy to Google Cloud and Heroku
matrix:
  include:
    - language: java
      jdk: oraclejdk8
      # Environment Variables
      env:
        before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
        cache:
          directories:
            - $HOME/.gradle/caches/
            - $HOME/.gradle/wrapper/
        script:
          - gradle assemble
          - gradle clean
          - ./bin/start.sh
        install: true